import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Brain } from 'lucide-react';

interface IntelligentBrandingModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const IntelligentBrandingModal: React.FC<IntelligentBrandingModalProps> = ({ isOpen, onClose }) => {
  const brandingFeatures = [
    {
      title: 'Adaptive Logos',
      definition: 'Logos that automatically adjust their size, layout, complexity, or color to fit different platforms and screen sizes.',
      useCases: [
        'Full logo for desktop, simplified icon for mobile',
        'Color inversion for dark/light mode',
        'Animated logos for digital media, static for print'
      ],
      whyItMatters: 'Ensures brand consistency while improving usability and aesthetics across all touchpoints (e.g., website, social media, packaging).',
      color: 'purple',
      emoji: '🔄'
    },
    {
      title: 'Smart Color Palettes',
      definition: 'AI-driven or data-informed color systems that adapt to user preferences, context, or platform themes (e.g., auto-dark mode support).',
      useCases: [
        'Dynamic branding that changes with seasons or user behavior',
        'Palettes that meet accessibility standards (e.g., contrast ratios)',
        'Real-time adjustments based on engagement analytics'
      ],
      whyItMatters: 'Helps brands stay fresh, context-aware, and inclusive without manual redesigns.',
      color: 'pink',
      emoji: '🎨'
    },
    {
      title: 'AI Typography',
      definition: 'Fonts and typographic systems selected or generated by AI to maximize readability, style, and emotional impact.',
      useCases: [
        'Headlines that auto-adjust size and weight based on device type',
        'AI-generated font pairings that reflect brand personality',
        'Responsive type that adjusts to user mood or interaction'
      ],
      whyItMatters: 'Enhances communication effectiveness and elevates the visual identity using real-time optimization.',
      color: 'blue',
      emoji: '🔤'
    },
    {
      title: 'Brand Evolution Tracking',
      definition: 'AI tools that monitor brand assets (logos, colors, voice, messaging) across platforms and measure their evolution and consistency over time.',
      useCases: [
        'See how your logo or tone of voice has changed over months/years',
        'Analytics dashboards showing user sentiment or visual consistency',
        'Notifications when brand usage deviates from guidelines'
      ],
      whyItMatters: 'Maintains brand integrity, identifies what works, and supports data-informed decisions during rebranding or scaling.',
      color: 'emerald',
      emoji: '📈'
    }
  ];

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-slate-900/90 backdrop-blur-xl z-50 flex items-center justify-center p-4"
          onClick={onClose}
        >
          <motion.div
            initial={{ scale: 0.9, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0, y: 20 }}
            transition={{ type: "spring", duration: 0.5 }}
            className="bg-slate-800/95 backdrop-blur-xl border border-slate-700/50 rounded-3xl p-8 max-w-6xl w-full max-h-[90vh] overflow-y-auto relative"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Close Button */}
            <motion.button
              whileHover={{ scale: 1.1, rotate: 90 }}
              whileTap={{ scale: 0.9 }}
              onClick={onClose}
              className="absolute top-6 right-6 w-12 h-12 bg-slate-700/50 hover:bg-slate-700 rounded-full flex items-center justify-center text-slate-400 hover:text-white transition-all duration-300 z-10"
            >
              <X size={24} />
            </motion.button>

            {/* Header */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-center mb-12"
            >
              <div className="flex items-center justify-center space-x-4 mb-6">
                <div className="w-16 h-16 bg-gradient-to-br from-purple-500/20 to-pink-500/20 border border-purple-500/30 rounded-2xl flex items-center justify-center">
                  <Brain className="text-purple-400" size={32} />
                </div>
                <h2 className="text-4xl font-bold text-white">
                  Intelligent{' '}
                  <span className="bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
                    Branding
                  </span>
                </h2>
              </div>
              <p className="text-xl text-slate-400 max-w-3xl mx-auto">
                Discover how AI-powered branding systems adapt, evolve, and optimize your brand identity 
                across all platforms and touchpoints.
              </p>
            </motion.div>

            {/* Features Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              {brandingFeatures.map((feature, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.2 + index * 0.1 }}
                  className="bg-slate-700/30 backdrop-blur-xl border border-slate-600/50 rounded-2xl p-8 hover:bg-slate-700/40 transition-all duration-300"
                >
                  {/* Feature Header */}
                  <div className="flex items-center space-x-4 mb-6">
                    <div className="text-3xl">{feature.emoji}</div>
                    <h3 className="text-2xl font-bold text-white">{feature.title}</h3>
                  </div>

                  {/* Definition */}
                  <div className="mb-6">
                    <h4 className="text-lg font-semibold text-purple-300 mb-3">Definition:</h4>
                    <p className="text-slate-300 leading-relaxed">{feature.definition}</p>
                  </div>

                  {/* Use Cases */}
                  <div className="mb-6">
                    <h4 className="text-lg font-semibold text-pink-300 mb-3">Use Case Examples:</h4>
                    <ul className="space-y-2">
                      {feature.useCases.map((useCase, useCaseIndex) => (
                        <li key={useCaseIndex} className="flex items-start space-x-3">
                          <div className="w-2 h-2 bg-gradient-to-r from-purple-400 to-pink-400 rounded-full mt-2 flex-shrink-0" />
                          <span className="text-slate-300 text-sm leading-relaxed">{useCase}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Why It Matters */}
                  <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-600/30">
                    <h4 className="text-lg font-semibold text-emerald-300 mb-2">Why It Matters:</h4>
                    <p className="text-slate-300 text-sm leading-relaxed">{feature.whyItMatters}</p>
                  </div>
                </motion.div>
              ))}
            </div>

            {/* Call to Action */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.8 }}
              className="text-center mt-12 p-8 bg-gradient-to-r from-purple-500/10 to-pink-500/10 border border-purple-500/20 rounded-2xl"
            >
              <h3 className="text-2xl font-bold text-white mb-4">
                Ready to Transform Your Brand with AI?
              </h3>
              <p className="text-slate-300 mb-6 max-w-2xl mx-auto">
                Let our neural networks analyze your brand and create an intelligent identity system 
                that adapts and evolves with your business.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  className="bg-gradient-to-r from-purple-500/30 to-pink-500/30 text-white px-8 py-3 rounded-xl font-medium hover:shadow-lg transition-all duration-300 border border-purple-500/20"
                >
                  Start Brand Analysis
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  className="border-2 border-slate-600/30 text-slate-300 px-8 py-3 rounded-xl font-medium hover:bg-slate-700/30 hover:text-white transition-all duration-300"
                >
                  View Case Studies
                </motion.button>
              </div>
            </motion.div>

            {/* Neural Animation Background */}
            <div className="absolute inset-0 pointer-events-none opacity-10 overflow-hidden rounded-3xl">
              <svg className="w-full h-full" viewBox="0 0 100 100">
                {Array.from({ length: 8 }, (_, i) => (
                  <motion.circle
                    key={i}
                    cx={10 + i * 12}
                    cy={20 + (i % 3) * 30}
                    r="1"
                    fill="url(#neuralGradient)"
                    animate={{
                      opacity: [0.3, 1, 0.3],
                      scale: [1, 1.5, 1]
                    }}
                    transition={{
                      duration: 2,
                      delay: i * 0.3,
                      repeat: Infinity,
                      ease: "easeInOut"
                    }}
                  />
                ))}
                <defs>
                  <linearGradient id="neuralGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0%" stopColor="#a855f7" />
                    <stop offset="50%" stopColor="#ec4899" />
                    <stop offset="100%" stopColor="#8b5cf6" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default IntelligentBrandingModal;